// world-atlas countries-10m.json 的 properties.name → { iso, zh, continent }
// 覆盖全部 UN 成员国 + 主要特别行政区/属地。未列出的由 build 脚本降级为 "其他洲" 并保留英文名。
// continent codes: AS=亚洲 EU=欧洲 NA=北美 SA=南美 AF=非洲 OC=大洋洲 AN=南极

export interface CountryMeta {
  iso: string;
  zh: string;
  continent: string;
}

export const CONTINENT_NAMES: Record<string, { name: string; nameEn: string }> = {
  AS: { name: '亚洲', nameEn: 'Asia' },
  EU: { name: '欧洲', nameEn: 'Europe' },
  NA: { name: '北美洲', nameEn: 'North America' },
  SA: { name: '南美洲', nameEn: 'South America' },
  AF: { name: '非洲', nameEn: 'Africa' },
  OC: { name: '大洋洲', nameEn: 'Oceania' },
  AN: { name: '南极洲', nameEn: 'Antarctica' },
  XX: { name: '其他', nameEn: 'Other' },
};

export const COUNTRY_META: Record<string, CountryMeta> = {
  // 亚洲
  // 港澳台属于中国，但作为独立「地区」展示（而非并列国家），名称带「中国」前缀
  'China': { iso: 'CN', zh: '中国', continent: 'AS' },
  'Hong Kong': { iso: 'HK', zh: '中国香港', continent: 'AS' },
  'Macao': { iso: 'MO', zh: '中国澳门', continent: 'AS' },
  'Taiwan': { iso: 'TW', zh: '中国台湾', continent: 'AS' },
  'Japan': { iso: 'JP', zh: '日本', continent: 'AS' },
  'South Korea': { iso: 'KR', zh: '韩国', continent: 'AS' },
  'North Korea': { iso: 'KP', zh: '朝鲜', continent: 'AS' },
  'Mongolia': { iso: 'MN', zh: '蒙古', continent: 'AS' },
  'Vietnam': { iso: 'VN', zh: '越南', continent: 'AS' },
  'Thailand': { iso: 'TH', zh: '泰国', continent: 'AS' },
  'Laos': { iso: 'LA', zh: '老挝', continent: 'AS' },
  'Cambodia': { iso: 'KH', zh: '柬埔寨', continent: 'AS' },
  'Myanmar': { iso: 'MM', zh: '缅甸', continent: 'AS' },
  'Malaysia': { iso: 'MY', zh: '马来西亚', continent: 'AS' },
  'Singapore': { iso: 'SG', zh: '新加坡', continent: 'AS' },
  'Indonesia': { iso: 'ID', zh: '印度尼西亚', continent: 'AS' },
  'Philippines': { iso: 'PH', zh: '菲律宾', continent: 'AS' },
  'Brunei': { iso: 'BN', zh: '文莱', continent: 'AS' },
  'Timor-Leste': { iso: 'TL', zh: '东帝汶', continent: 'AS' },
  'India': { iso: 'IN', zh: '印度', continent: 'AS' },
  'Pakistan': { iso: 'PK', zh: '巴基斯坦', continent: 'AS' },
  'Bangladesh': { iso: 'BD', zh: '孟加拉国', continent: 'AS' },
  'Sri Lanka': { iso: 'LK', zh: '斯里兰卡', continent: 'AS' },
  'Nepal': { iso: 'NP', zh: '尼泊尔', continent: 'AS' },
  'Bhutan': { iso: 'BT', zh: '不丹', continent: 'AS' },
  'Maldives': { iso: 'MV', zh: '马尔代夫', continent: 'AS' },
  'Afghanistan': { iso: 'AF', zh: '阿富汗', continent: 'AS' },
  'Iran': { iso: 'IR', zh: '伊朗', continent: 'AS' },
  'Iraq': { iso: 'IQ', zh: '伊拉克', continent: 'AS' },
  'Syria': { iso: 'SY', zh: '叙利亚', continent: 'AS' },
  'Lebanon': { iso: 'LB', zh: '黎巴嫩', continent: 'AS' },
  'Jordan': { iso: 'JO', zh: '约旦', continent: 'AS' },
  'Israel': { iso: 'IL', zh: '以色列', continent: 'AS' },
  'Palestine': { iso: 'PS', zh: '巴勒斯坦', continent: 'AS' },
  'Saudi Arabia': { iso: 'SA', zh: '沙特阿拉伯', continent: 'AS' },
  'Yemen': { iso: 'YE', zh: '也门', continent: 'AS' },
  'Oman': { iso: 'OM', zh: '阿曼', continent: 'AS' },
  'United Arab Emirates': { iso: 'AE', zh: '阿联酋', continent: 'AS' },
  'Qatar': { iso: 'QA', zh: '卡塔尔', continent: 'AS' },
  'Bahrain': { iso: 'BH', zh: '巴林', continent: 'AS' },
  'Kuwait': { iso: 'KW', zh: '科威特', continent: 'AS' },
  'Turkey': { iso: 'TR', zh: '土耳其', continent: 'AS' },
  'Cyprus': { iso: 'CY', zh: '塞浦路斯', continent: 'EU' },
  'N. Cyprus': { iso: 'CY', zh: '北塞浦路斯', continent: 'EU' },
  'Azerbaijan': { iso: 'AZ', zh: '阿塞拜疆', continent: 'AS' },
  'Armenia': { iso: 'AM', zh: '亚美尼亚', continent: 'AS' },
  'Georgia': { iso: 'GE', zh: '格鲁吉亚', continent: 'AS' },
  'Kazakhstan': { iso: 'KZ', zh: '哈萨克斯坦', continent: 'AS' },
  'Uzbekistan': { iso: 'UZ', zh: '乌兹别克斯坦', continent: 'AS' },
  'Turkmenistan': { iso: 'TM', zh: '土库曼斯坦', continent: 'AS' },
  'Kyrgyzstan': { iso: 'KG', zh: '吉尔吉斯斯坦', continent: 'AS' },
  'Tajikistan': { iso: 'TJ', zh: '塔吉克斯坦', continent: 'AS' },

  // 欧洲
  'United Kingdom': { iso: 'GB', zh: '英国', continent: 'EU' },
  'Ireland': { iso: 'IE', zh: '爱尔兰', continent: 'EU' },
  'France': { iso: 'FR', zh: '法国', continent: 'EU' },
  'Germany': { iso: 'DE', zh: '德国', continent: 'EU' },
  'Italy': { iso: 'IT', zh: '意大利', continent: 'EU' },
  'Spain': { iso: 'ES', zh: '西班牙', continent: 'EU' },
  'Portugal': { iso: 'PT', zh: '葡萄牙', continent: 'EU' },
  'Netherlands': { iso: 'NL', zh: '荷兰', continent: 'EU' },
  'Belgium': { iso: 'BE', zh: '比利时', continent: 'EU' },
  'Luxembourg': { iso: 'LU', zh: '卢森堡', continent: 'EU' },
  'Switzerland': { iso: 'CH', zh: '瑞士', continent: 'EU' },
  'Austria': { iso: 'AT', zh: '奥地利', continent: 'EU' },
  'Liechtenstein': { iso: 'LI', zh: '列支敦士登', continent: 'EU' },
  'Monaco': { iso: 'MC', zh: '摩纳哥', continent: 'EU' },
  'Andorra': { iso: 'AD', zh: '安道尔', continent: 'EU' },
  'San Marino': { iso: 'SM', zh: '圣马力诺', continent: 'EU' },
  'Vatican': { iso: 'VA', zh: '梵蒂冈', continent: 'EU' },
  'Malta': { iso: 'MT', zh: '马耳他', continent: 'EU' },
  'Greece': { iso: 'GR', zh: '希腊', continent: 'EU' },
  'Albania': { iso: 'AL', zh: '阿尔巴尼亚', continent: 'EU' },
  'Macedonia': { iso: 'MK', zh: '北马其顿', continent: 'EU' },
  'Kosovo': { iso: 'XK', zh: '科索沃', continent: 'EU' },
  'Montenegro': { iso: 'ME', zh: '黑山', continent: 'EU' },
  'Serbia': { iso: 'RS', zh: '塞尔维亚', continent: 'EU' },
  'Bosnia and Herz.': { iso: 'BA', zh: '波黑', continent: 'EU' },
  'Croatia': { iso: 'HR', zh: '克罗地亚', continent: 'EU' },
  'Slovenia': { iso: 'SI', zh: '斯洛文尼亚', continent: 'EU' },
  'Hungary': { iso: 'HU', zh: '匈牙利', continent: 'EU' },
  'Romania': { iso: 'RO', zh: '罗马尼亚', continent: 'EU' },
  'Bulgaria': { iso: 'BG', zh: '保加利亚', continent: 'EU' },
  'Moldova': { iso: 'MD', zh: '摩尔多瓦', continent: 'EU' },
  'Ukraine': { iso: 'UA', zh: '乌克兰', continent: 'EU' },
  'Belarus': { iso: 'BY', zh: '白俄罗斯', continent: 'EU' },
  'Russia': { iso: 'RU', zh: '俄罗斯', continent: 'EU' },
  'Poland': { iso: 'PL', zh: '波兰', continent: 'EU' },
  'Czechia': { iso: 'CZ', zh: '捷克', continent: 'EU' },
  'Slovakia': { iso: 'SK', zh: '斯洛伐克', continent: 'EU' },
  'Lithuania': { iso: 'LT', zh: '立陶宛', continent: 'EU' },
  'Latvia': { iso: 'LV', zh: '拉脱维亚', continent: 'EU' },
  'Estonia': { iso: 'EE', zh: '爱沙尼亚', continent: 'EU' },
  'Finland': { iso: 'FI', zh: '芬兰', continent: 'EU' },
  'Sweden': { iso: 'SE', zh: '瑞典', continent: 'EU' },
  'Norway': { iso: 'NO', zh: '挪威', continent: 'EU' },
  'Denmark': { iso: 'DK', zh: '丹麦', continent: 'EU' },
  'Iceland': { iso: 'IS', zh: '冰岛', continent: 'EU' },
  'Faeroe Is.': { iso: 'FO', zh: '法罗群岛', continent: 'EU' },
  'Isle of Man': { iso: 'IM', zh: '马恩岛', continent: 'EU' },
  'Jersey': { iso: 'JE', zh: '泽西岛', continent: 'EU' },
  'Guernsey': { iso: 'GG', zh: '根西岛', continent: 'EU' },
  'Åland': { iso: 'AX', zh: '奥兰群岛', continent: 'EU' },
  'Gibraltar': { iso: 'GI', zh: '直布罗陀', continent: 'EU' },

  // 北美洲
  'United States of America': { iso: 'US', zh: '美国', continent: 'NA' },
  'Canada': { iso: 'CA', zh: '加拿大', continent: 'NA' },
  'Mexico': { iso: 'MX', zh: '墨西哥', continent: 'NA' },
  'Greenland': { iso: 'GL', zh: '格陵兰', continent: 'NA' },
  'Bermuda': { iso: 'BM', zh: '百慕大', continent: 'NA' },
  'Guatemala': { iso: 'GT', zh: '危地马拉', continent: 'NA' },
  'Belize': { iso: 'BZ', zh: '伯利兹', continent: 'NA' },
  'El Salvador': { iso: 'SV', zh: '萨尔瓦多', continent: 'NA' },
  'Honduras': { iso: 'HN', zh: '洪都拉斯', continent: 'NA' },
  'Nicaragua': { iso: 'NI', zh: '尼加拉瓜', continent: 'NA' },
  'Costa Rica': { iso: 'CR', zh: '哥斯达黎加', continent: 'NA' },
  'Panama': { iso: 'PA', zh: '巴拿马', continent: 'NA' },
  'Cuba': { iso: 'CU', zh: '古巴', continent: 'NA' },
  'Jamaica': { iso: 'JM', zh: '牙买加', continent: 'NA' },
  'Haiti': { iso: 'HT', zh: '海地', continent: 'NA' },
  'Dominican Rep.': { iso: 'DO', zh: '多米尼加', continent: 'NA' },
  'Puerto Rico': { iso: 'PR', zh: '波多黎各', continent: 'NA' },
  'Bahamas': { iso: 'BS', zh: '巴哈马', continent: 'NA' },
  'Barbados': { iso: 'BB', zh: '巴巴多斯', continent: 'NA' },
  'Trinidad and Tobago': { iso: 'TT', zh: '特立尼达和多巴哥', continent: 'NA' },
  'Grenada': { iso: 'GD', zh: '格林纳达', continent: 'NA' },
  'Dominica': { iso: 'DM', zh: '多米尼克', continent: 'NA' },
  'Saint Lucia': { iso: 'LC', zh: '圣卢西亚', continent: 'NA' },
  'St. Vin. and Gren.': { iso: 'VC', zh: '圣文森特和格林纳丁斯', continent: 'NA' },
  'St. Kitts and Nevis': { iso: 'KN', zh: '圣基茨和尼维斯', continent: 'NA' },
  'Antigua and Barb.': { iso: 'AG', zh: '安提瓜和巴布达', continent: 'NA' },
  'Cayman Is.': { iso: 'KY', zh: '开曼群岛', continent: 'NA' },
  'Turks and Caicos Is.': { iso: 'TC', zh: '特克斯和凯科斯', continent: 'NA' },
  'British Virgin Is.': { iso: 'VG', zh: '英属维尔京群岛', continent: 'NA' },
  'U.S. Virgin Is.': { iso: 'VI', zh: '美属维尔京群岛', continent: 'NA' },
  'Aruba': { iso: 'AW', zh: '阿鲁巴', continent: 'NA' },
  'Curaçao': { iso: 'CW', zh: '库拉索', continent: 'NA' },
  'Sint Maarten': { iso: 'SX', zh: '荷属圣马丁', continent: 'NA' },
  'Anguilla': { iso: 'AI', zh: '安圭拉', continent: 'NA' },
  'Montserrat': { iso: 'MS', zh: '蒙特塞拉特', continent: 'NA' },

  // 南美洲
  'Brazil': { iso: 'BR', zh: '巴西', continent: 'SA' },
  'Argentina': { iso: 'AR', zh: '阿根廷', continent: 'SA' },
  'Chile': { iso: 'CL', zh: '智利', continent: 'SA' },
  'Peru': { iso: 'PE', zh: '秘鲁', continent: 'SA' },
  'Colombia': { iso: 'CO', zh: '哥伦比亚', continent: 'SA' },
  'Venezuela': { iso: 'VE', zh: '委内瑞拉', continent: 'SA' },
  'Ecuador': { iso: 'EC', zh: '厄瓜多尔', continent: 'SA' },
  'Bolivia': { iso: 'BO', zh: '玻利维亚', continent: 'SA' },
  'Paraguay': { iso: 'PY', zh: '巴拉圭', continent: 'SA' },
  'Uruguay': { iso: 'UY', zh: '乌拉圭', continent: 'SA' },
  'Guyana': { iso: 'GY', zh: '圭亚那', continent: 'SA' },
  'Suriname': { iso: 'SR', zh: '苏里南', continent: 'SA' },
  'Falkland Is.': { iso: 'FK', zh: '福克兰群岛', continent: 'SA' },

  // 大洋洲
  'Australia': { iso: 'AU', zh: '澳大利亚', continent: 'OC' },
  'New Zealand': { iso: 'NZ', zh: '新西兰', continent: 'OC' },
  'Papua New Guinea': { iso: 'PG', zh: '巴布亚新几内亚', continent: 'OC' },
  'Fiji': { iso: 'FJ', zh: '斐济', continent: 'OC' },
  'Solomon Is.': { iso: 'SB', zh: '所罗门群岛', continent: 'OC' },
  'Vanuatu': { iso: 'VU', zh: '瓦努阿图', continent: 'OC' },
  'Samoa': { iso: 'WS', zh: '萨摩亚', continent: 'OC' },
  'Tonga': { iso: 'TO', zh: '汤加', continent: 'OC' },
  'Kiribati': { iso: 'KI', zh: '基里巴斯', continent: 'OC' },
  'Tuvalu': { iso: 'TV', zh: '图瓦卢', continent: 'OC' },
  'Nauru': { iso: 'NR', zh: '瑙鲁', continent: 'OC' },
  'Palau': { iso: 'PW', zh: '帕劳', continent: 'OC' },
  'Marshall Is.': { iso: 'MH', zh: '马绍尔群岛', continent: 'OC' },
  'Micronesia': { iso: 'FM', zh: '密克罗尼西亚', continent: 'OC' },
  'Cook Is.': { iso: 'CK', zh: '库克群岛', continent: 'OC' },
  'Niue': { iso: 'NU', zh: '纽埃', continent: 'OC' },
  'New Caledonia': { iso: 'NC', zh: '新喀里多尼亚', continent: 'OC' },
  'Fr. Polynesia': { iso: 'PF', zh: '法属波利尼西亚', continent: 'OC' },
  'American Samoa': { iso: 'AS', zh: '美属萨摩亚', continent: 'OC' },
  'Guam': { iso: 'GU', zh: '关岛', continent: 'OC' },
  'N. Mariana Is.': { iso: 'MP', zh: '北马里亚纳群岛', continent: 'OC' },

  // 非洲
  'Egypt': { iso: 'EG', zh: '埃及', continent: 'AF' },
  'Libya': { iso: 'LY', zh: '利比亚', continent: 'AF' },
  'Tunisia': { iso: 'TN', zh: '突尼斯', continent: 'AF' },
  'Algeria': { iso: 'DZ', zh: '阿尔及利亚', continent: 'AF' },
  'Morocco': { iso: 'MA', zh: '摩洛哥', continent: 'AF' },
  'W. Sahara': { iso: 'EH', zh: '西撒哈拉', continent: 'AF' },
  'Mauritania': { iso: 'MR', zh: '毛里塔尼亚', continent: 'AF' },
  'Mali': { iso: 'ML', zh: '马里', continent: 'AF' },
  'Niger': { iso: 'NE', zh: '尼日尔', continent: 'AF' },
  'Chad': { iso: 'TD', zh: '乍得', continent: 'AF' },
  'Sudan': { iso: 'SD', zh: '苏丹', continent: 'AF' },
  'S. Sudan': { iso: 'SS', zh: '南苏丹', continent: 'AF' },
  'Ethiopia': { iso: 'ET', zh: '埃塞俄比亚', continent: 'AF' },
  'Eritrea': { iso: 'ER', zh: '厄立特里亚', continent: 'AF' },
  'Djibouti': { iso: 'DJ', zh: '吉布提', continent: 'AF' },
  'Somalia': { iso: 'SO', zh: '索马里', continent: 'AF' },
  'Somaliland': { iso: 'SO', zh: '索马里兰', continent: 'AF' },
  'Kenya': { iso: 'KE', zh: '肯尼亚', continent: 'AF' },
  'Uganda': { iso: 'UG', zh: '乌干达', continent: 'AF' },
  'Rwanda': { iso: 'RW', zh: '卢旺达', continent: 'AF' },
  'Burundi': { iso: 'BI', zh: '布隆迪', continent: 'AF' },
  'Tanzania': { iso: 'TZ', zh: '坦桑尼亚', continent: 'AF' },
  'Malawi': { iso: 'MW', zh: '马拉维', continent: 'AF' },
  'Zambia': { iso: 'ZM', zh: '赞比亚', continent: 'AF' },
  'Zimbabwe': { iso: 'ZW', zh: '津巴布韦', continent: 'AF' },
  'Mozambique': { iso: 'MZ', zh: '莫桑比克', continent: 'AF' },
  'Madagascar': { iso: 'MG', zh: '马达加斯加', continent: 'AF' },
  'Mauritius': { iso: 'MU', zh: '毛里求斯', continent: 'AF' },
  'Seychelles': { iso: 'SC', zh: '塞舌尔', continent: 'AF' },
  'Comoros': { iso: 'KM', zh: '科摩罗', continent: 'AF' },
  'South Africa': { iso: 'ZA', zh: '南非', continent: 'AF' },
  'Lesotho': { iso: 'LS', zh: '莱索托', continent: 'AF' },
  'eSwatini': { iso: 'SZ', zh: '斯威士兰', continent: 'AF' },
  'Botswana': { iso: 'BW', zh: '博茨瓦纳', continent: 'AF' },
  'Namibia': { iso: 'NA', zh: '纳米比亚', continent: 'AF' },
  'Angola': { iso: 'AO', zh: '安哥拉', continent: 'AF' },
  'Dem. Rep. Congo': { iso: 'CD', zh: '刚果（金）', continent: 'AF' },
  'Congo': { iso: 'CG', zh: '刚果（布）', continent: 'AF' },
  'Gabon': { iso: 'GA', zh: '加蓬', continent: 'AF' },
  'Eq. Guinea': { iso: 'GQ', zh: '赤道几内亚', continent: 'AF' },
  'Cameroon': { iso: 'CM', zh: '喀麦隆', continent: 'AF' },
  'Central African Rep.': { iso: 'CF', zh: '中非', continent: 'AF' },
  'Nigeria': { iso: 'NG', zh: '尼日利亚', continent: 'AF' },
  'Benin': { iso: 'BJ', zh: '贝宁', continent: 'AF' },
  'Togo': { iso: 'TG', zh: '多哥', continent: 'AF' },
  'Ghana': { iso: 'GH', zh: '加纳', continent: 'AF' },
  'Côte d\'Ivoire': { iso: 'CI', zh: '科特迪瓦', continent: 'AF' },
  'Liberia': { iso: 'LR', zh: '利比里亚', continent: 'AF' },
  'Sierra Leone': { iso: 'SL', zh: '塞拉利昂', continent: 'AF' },
  'Guinea': { iso: 'GN', zh: '几内亚', continent: 'AF' },
  'Guinea-Bissau': { iso: 'GW', zh: '几内亚比绍', continent: 'AF' },
  'Senegal': { iso: 'SN', zh: '塞内加尔', continent: 'AF' },
  'Gambia': { iso: 'GM', zh: '冈比亚', continent: 'AF' },
  'Cabo Verde': { iso: 'CV', zh: '佛得角', continent: 'AF' },
  'Burkina Faso': { iso: 'BF', zh: '布基纳法索', continent: 'AF' },
  'São Tomé and Principe': { iso: 'ST', zh: '圣多美和普林西比', continent: 'AF' },
  'Saint Helena': { iso: 'SH', zh: '圣赫勒拿', continent: 'AF' },

  // 南极
  'Antarctica': { iso: 'AQ', zh: '南极洲', continent: 'AN' },
};

export function getCountryMeta(name: string): CountryMeta {
  return COUNTRY_META[name] ?? { iso: 'XX', zh: name, continent: 'XX' };
}
