// 反向地理编码工具：把 places.json 里仍以经纬度显示的 "cities" 反查成中文地名，
// 输出 scripts/known-cities-auto.ts。用法：
//   1) 先跑 `npm run build:data` 生成 public/data/places.json
//   2) 跑 `npx tsx scripts/fetch-city-names.ts`
//   3) 再跑 `npm run build:data` 让新地名生效
// Nominatim 公共服务限流 1 req/s，本脚本严格串行 + 1.2s 间隔。
import fs from 'node:fs';
import path from 'node:path';

interface PlaceCity { name: string; lat: number; lon: number; count: number }
interface PlaceCountry { name: string; cities: PlaceCity[] }
interface PlaceContinent { countries: PlaceCountry[] }
interface Places { continents: PlaceContinent[] }

const ROOT = path.resolve(new URL('..', import.meta.url).pathname);
const PLACES = path.join(ROOT, 'public/data/places.json');
const OUT = path.join(ROOT, 'scripts/known-cities-auto.ts');
const CACHE = path.join(ROOT, 'scripts/city-cache.json');

if (!fs.existsSync(PLACES)) {
  console.error('✗ places.json not found. Run `npm run build:data` first.');
  process.exit(1);
}

const places = JSON.parse(fs.readFileSync(PLACES, 'utf8')) as Places;
const cache: Record<string, string | null> = fs.existsSync(CACHE)
  ? JSON.parse(fs.readFileSync(CACHE, 'utf8'))
  : {};

// 收集所有以 "LAT, LON" 格式的 city（未匹配已知城市的）
const coordRe = /^-?\d+\.\d+,\s*-?\d+\.\d+$/;
type Target = { lat: number; lon: number; count: number };
const targets: Target[] = [];
for (const c of places.continents) {
  for (const co of c.countries) {
    for (const city of co.cities) {
      if (coordRe.test(city.name)) {
        targets.push({ lat: city.lat, lon: city.lon, count: city.count });
      }
    }
  }
}
// 按 count 降序
targets.sort((a, b) => b.count - a.count);
console.log(`Found ${targets.length} unnamed grids`);

const UA = 'travel-map-reverse-geocode/1.0 (contact: local-build)';

async function reverse(lat: number, lon: number): Promise<string | null> {
  const key = `${lat.toFixed(4)},${lon.toFixed(4)}`;
  if (Object.prototype.hasOwnProperty.call(cache, key)) return cache[key];

  const url = `https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}&zoom=8&accept-language=zh-CN`;
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA, 'Accept-Language': 'zh-CN' } });
    if (!res.ok) throw new Error(`http ${res.status}`);
    const d = await res.json() as {
      name?: string;
      address?: { city?: string; town?: string; village?: string; county?: string; state_district?: string; state?: string; municipality?: string };
    };
    const a = d.address ?? {};
    // 优先级：name (zoom=8 通常是县/区级) > city > town > village > county > state_district > state
    const picked =
      d.name ||
      a.city ||
      a.municipality ||
      a.town ||
      a.village ||
      a.county ||
      a.state_district ||
      a.state ||
      null;
    cache[key] = picked;
    return picked;
  } catch (e) {
    console.warn(`  ✗ ${lat},${lon}:`, (e as Error).message);
    cache[key] = null;
    return null;
  }
}

function trimName(name: string): string {
  // 去掉末尾的 "县"/"市"/"区" 等常见行政级别后缀有时看起来更简洁，但也可能歧义。
  // 这里保守保留全名，用户认为冗余可再手编。
  return name.trim();
}

async function main() {
  const results: { lat: number; lon: number; name: string; count: number }[] = [];
  let processed = 0;
  for (const t of targets) {
    processed++;
    const name = await reverse(t.lat, t.lon);
    if (name) {
      results.push({ lat: t.lat, lon: t.lon, name: trimName(name), count: t.count });
      console.log(`  [${processed}/${targets.length}] ${t.lat},${t.lon} (${t.count}) → ${name}`);
    } else {
      console.log(`  [${processed}/${targets.length}] ${t.lat},${t.lon} (${t.count}) → (no name)`);
    }
    // 每次写一遍 cache，避免中断丢进度
    fs.writeFileSync(CACHE, JSON.stringify(cache, null, 2));
    // Nominatim 免费服务限流：1 req/s，留点 margin
    await new Promise((r) => setTimeout(r, 1200));
  }

  // 输出 known-cities-auto.ts
  const body = [
    '// Auto-generated by scripts/fetch-city-names.ts via Nominatim reverse geocoding.',
    '// 手动修改请改 scripts/known-cities.ts 或此文件后重跑 build:data。',
    '',
    'export const autoCities: { name: string; lat: number; lon: number }[] = [',
    ...results.map((r) => `  { name: ${JSON.stringify(r.name)}, lat: ${r.lat}, lon: ${r.lon} },  // ${r.count} points`),
    '];',
    '',
  ].join('\n');
  fs.writeFileSync(OUT, body);
  console.log(`\n✓ wrote ${OUT} with ${results.length} entries`);
}

main();
