// Auto-generated by scripts/fetch-city-names.ts via Nominatim reverse geocoding.
// 手动修改请改 scripts/known-cities.ts 或此文件后重跑 build:data。

export const autoCities: { name: string; lat: number; lon: number }[] = [
  { name: "卡什", lat: 36.2185, lon: 29.5159 },  // 383 points
  { name: "棉花堡", lat: 37.9285, lon: 29.1212 },  // 366 points
  { name: "布尔津县", lat: 48.5975, lon: 87.0684 },  // 307 points
  { name: "费特希耶", lat: 36.5509, lon: 29.1248 },  // 270 points
  { name: "南部县", lat: 31.4948, lon: 105.5227 },  // 217 points
  { name: "武陵源区", lat: 29.358, lon: 110.4807 },  // 185 points
  { name: "博乐市", lat: 44.6895, lon: 81.1043 },  // 180 points
  { name: "旺苍县", lat: 32.0106, lon: 106.4679 },  // 167 points
  { name: "宜君县", lat: 35.4573, lon: 109.0511 },  // 159 points
  { name: "盂县", lat: 38.0541, lon: 113.4666 },  // 156 points
  { name: "石楼县", lat: 37.0265, lon: 111.0195 },  // 141 points
  { name: "阿克萨赖", lat: 38.3795, lon: 34.0003 },  // 141 points
  { name: "富县", lat: 35.9836, lon: 109.4601 },  // 136 points
  { name: "南江县", lat: 32.4845, lon: 107.017 },  // 131 points
  { name: "延长县", lat: 36.5709, lon: 110.0178 },  // 127 points
  { name: "佛坪县", lat: 33.4828, lon: 108.1003 },  // 123 points
  { name: "苍溪县", lat: 31.8926, lon: 106.0215 },  // 120 points
  { name: "镇巴县", lat: 32.4622, lon: 107.4519 },  // 118 points
  { name: "孝义市", lat: 37.075, lon: 111.5036 },  // 113 points
  { name: "阜平县", lat: 39.0073, lon: 114.0633 },  // 112 points
  { name: "石楼县", lat: 36.8811, lon: 110.5056 },  // 108 points
  { name: "博乐市", lat: 44.6245, lon: 81.3375 },  // 105 points
  { name: "涞源县", lat: 39.5856, lon: 115.0052 },  // 104 points
  { name: "离石区", lat: 37.4157, lon: 111.493 },  // 104 points
  { name: "西乡县", lat: 32.9001, lon: 107.5772 },  // 100 points
  { name: "涞源县", lat: 39.3811, lon: 114.4992 },  // 97 points
  { name: "大宁县", lat: 36.4374, lon: 110.4955 },  // 96 points
  { name: "宜川县", lat: 36.1289, lon: 109.9753 },  // 86 points
  { name: "宝塔区", lat: 36.3686, lon: 109.5668 },  // 85 points
  { name: "南江县", lat: 32.1334, lon: 106.9577 },  // 72 points
  { name: "门头沟区", lat: 39.8462, lon: 115.5858 },  // 69 points
  { name: "富县", lat: 35.8945, lon: 109.171 },  // 67 points
  { name: "Sultanhanı", lat: 38.256, lon: 33.5426 },  // 67 points
  { name: "埃斯基爾", lat: 38.2352, lon: 33.4826 },  // 64 points
  { name: "布尔津县", lat: 48.5708, lon: 87.4302 },  // 63 points
  { name: "黄陵县", lat: 35.6096, lon: 109.3104 },  // 61 points
  { name: "隰县", lat: 36.6581, lon: 110.9 },  // 55 points
  { name: "西乡县", lat: 33.159, lon: 107.8368 },  // 53 points
  { name: "襄都区", lat: 37.0016, lon: 114.566 },  // 52 points
  { name: "成安县", lat: 36.4814, lon: 114.5239 },  // 51 points
  { name: "平城区", lat: 40.0767, lon: 113.3116 },  // 48 points
  { name: "三台县", lat: 31.3245, lon: 105.2059 },  // 48 points
  { name: "永定区", lat: 29.1212, lon: 110.4472 },  // 39 points
  { name: "华阴市", lat: 34.5612, lon: 109.9921 },  // 38 points
  { name: "旺苍县", lat: 32.3042, lon: 106.6725 },  // 38 points
  { name: "镇巴县", lat: 32.4727, lon: 107.8675 },  // 37 points
  { name: "卫辉市", lat: 35.4302, lon: 114.0681 },  // 36 points
  { name: "平谷区", lat: 40.1811, lon: 117.3045 },  // 35 points
  { name: "平山县", lat: 38.2857, lon: 113.6691 },  // 35 points
  { name: "阿勒泰市", lat: 47.7908, lon: 87.9807 },  // 34 points
  { name: "乌尔禾区", lat: 46.1232, lon: 85.7316 },  // 34 points
  { name: "灵宝市", lat: 34.5774, lon: 110.5351 },  // 34 points
  { name: "Cuautepec de Hinojosa", lat: 19.9943, lon: -98.317 },  // 33 points
  { name: "绵竹市", lat: 31.4108, lon: 104.1995 },  // 31 points
];
